name: Manual Install and Run with Maven

on:
  workflow_dispatch:
    inputs:
      java_version:
        description: 'Java version to use'
        required: true
        default: '11'

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: ${{ github.event.inputs.java_version }}
          distribution: 'temurin'
          cache: 'maven'

      - name: Build with Maven
        run: mvn clean install -e -B

      - name: Run Java program
        run: mvn exec:java -Dexec.mainClass="com.example.Index"

      - name: Create log directory
        run: mkdir -p ${{ runner.workspace }}/logs

      - name: Save logs
        run: mvn clean install -e -B | tee ${{ runner.workspace }}/logs/generator_log.txt

      - name: Upload log file
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: generator-log
          path: ${{ runner.workspace }}/logs/generator_log.txt
        continue-on-error: true