name: Manual Install and Run with Maven

on:
  workflow_dispatch:
    inputs:
      java_version:
        description: 'Java version to use'
        required: true
        default: '11'
      log_level:
        description: 'Log level for the run'
        required: false
        default: 'info'

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: ${{ github.event.inputs.java_version }}
          distribution: 'temurin'
          cache: 'maven'

      - name: Build with Maven
        run: mvn clean install -e -B  # -X 改为 -B 以减少冗长输出，除非需要调试

      - name: Run Java program
        run: |
          mvn exec:java -Dexec.mainClass="cn.sixTail.tyme4j.Index" \
            -Dlog.level=${{ github.event.inputs.log_level }}
        env:
          JAVA_OPTS: "-Xmx512m"  # 设置运行时的内存限制

      - name: Upload log file
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: generator-log
          path: ${{ runner.workspace }}/tyme4j-generator/logs/generator_log.txt  # 更新为实际日志路径
        continue-on-error: true  # 即使上传失败也不终止工作流