name: Manual Install and Run with Maven

on:
  workflow_dispatch:
    inputs:
      java_version:
        description: 'Java version to use'
        required: true
        default: '1.8'  # 强制默认使用 Java 8
      log_level:
        description: 'Log level for the run'
        required: false
        default: 'info'

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: ${{ github.event.inputs.java_version }}
          distribution: 'temurin'
          cache: 'maven'

      - name: Build with Maven (Debug Mode)
        run: mvn clean install -e -X  # 使用 -e 输出错误堆栈，-X 启用调试日志

      - name: Run Java program
        run: mvn exec:java -Dexec.mainClass="cn.6tail.tyme4j.Index"  # 确保使用全限定类名

      - name: Upload log file
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: generator-log
          path: generator_log.txt  # 确保日志文件路径正确